### ISSUE TITLE
Memory leak when scanning large table

### ISSUE THREAD

**Issue by clusterfudge** [googleapis/google-cloud-python-happybase#32]
I'm currently using bigtable for archival of tsdb data. When attempting to restore, I find that I have to frequently release the table.scan() cursor, or my memory usage skyrockets (will consume 32gb within an hour). With checkpointing in place and new cursors, I am not seeing this issue. Is this working as intended?

I've created 2 gists to demonstrate the behavior, both of which assume they're running on a GCE instance with local instance credentials granted the necessary BT roles.
https://gist.github.com/clusterfudge/3fe40f7f55e8a2a80c65dbd8e8d6764e - implements checkpointing, has a reasonable and stable memory footprint

https://gist.github.com/clusterfudge/3a2e6b484d24070b6f43fd3fd989e229 - simple single call to scan, will consume all memory available, stopped only by the heat death of the universe.

**Comment by sduskis** [comment]
This is in progress.  We will use `table.read_rows` as a generator, which does not store any variables.

**Comment by clusterfudge** [comment]
thanks @sduskis , any eta?

**Comment by clusterfudge** [comment]
bump

**Comment by tseaver** [comment]
Closed in #42, released in [`google-cloud-happybase 0.30.2`](https://github.com/googleapis/google-cloud-python-happybase/releases/tag/0.30.2).
