### ISSUE TITLE
Update pypi release for `pip install google-cloud-happybase`

### ISSUE THREAD

**Issue by Froskekongen** [googleapis/google-cloud-python-happybase#38]
The release present in pypi (https://pypi.org/project/google-cloud-happybase/) is severely outdated. Please make a release reflecting the changes in the bigtable api.

**Comment by tseaver** [comment]
(0.26.0 was released](https://pypi.org/project/google-cloud-happybase/#history) 2018-08-07.

**Comment by tseaver** [comment]
My bad:  the release date was 2017-08-07.  I will make a release today.
