### ISSUE TITLE
Use 'MutationBatcher' in 'happybase.table.Batch'

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python-happybase#4]
Once https://github.com/GoogleCloudPlatform/gcloud-python/issues/1546 adds support for the `MutateRows` API.

**Comment by tseaver** [comment]
This one is too old:  `Table.send` does not even exist.

@sduskis Please reopen if you think it is relevant, and point to the right spot.

**Comment by mbrukman** [comment]
Looks like [`happybase.Table.batch()`][batch-method] returns an instance of [`happybase.Batch` class][batch-class] which has a [`happybase.Batch.put()`][put] method. Presumably, that's the method that should use `MutateRows()` once it reaches the predefined batch size.

[batch-method]: https://happybase.readthedocs.io/en/latest/api.html#happybase.Table.batch
[batch-class]: https://happybase.readthedocs.io/en/latest/api.html#batch
[put]: https://happybase.readthedocs.io/en/latest/api.html#happybase.Batch.put

**Comment by sduskis** [comment]
There's a new [`MutationBatcher`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/bigtable/google/cloud/bigtable/batcher.py) that ought to be used here.
