### ISSUE TITLE
Migrate to kokoro

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-python-happybase#43]
The tests in this repository are still using travis for CI.  We need to get this moved over to kokoro.

**Comment by tseaver** [comment]
@busunkim96 AFAICT, Kokoro is not running for this repository (see #66, for example).

**Comment by busunkim96** [comment]
@tseaver Yes, I'll look into what went wrong there. I'll manually run the kokoro job for the PR #66.

**Comment by busunkim96** [comment]
The Kokoro webhook has been created, jobs should now be triggered for PRs and merges to master.
