### ISSUE TITLE
System test leaking Bigtable instance

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python-happybase#45]
I just cleaned up a leaked instance, `gcl-hb-1533663867713` (no labels).

**Comment by sduskis** [comment]
@sumit-ql, can you please take a look at this?

**Comment by sumit-ql** [comment]
@tseaver Could you please point me out the logs of last successful system tests run. I am getting error while i am running system tests locally. 
Are the system tests running after each check-in.

**Comment by tseaver** [comment]
@sumit-ql Travis is not running the `tox -e system-tests` environment:  it runs only:

  - `tox -e py27`
  - `tox -e py34`
  - `tox -e lint`
  - `tox -e cover`

**Comment by sumit-ql** [comment]
yes that's correct. I will try to revamp the systems tests.

**Comment by meredithslota** [comment]
Seems closed by #53 - please reopen if needed.
