### ISSUE TITLE
'Connection' ctor uses missing `instance.copy`

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python-happybase#46]
From: https://github.com/googleapis/google-cloud-python-happybase/pull/41#issuecomment-425821509

https://github.com/googleapis/google-cloud-python/commit/86102c959c6852d6b02c2fe3ddeea946a003bee6#diff-7cb26d3f6a9d474a951ae6ff1af2ce71 removed `Instance.copy`, but the `Connection` constructor [still uses it](https://github.com/googleapis/google-cloud-python-happybase/blob/24de0cbe5edbcde13c213148b9a0652733b92e17/src/google/cloud/happybase/connection.py#L175).

**Comment by clusterfudge** [comment]
This is still present in 0.31.0 release.

**Comment by sduskis** [comment]
@sumit-ql, can you please take a look at this?

**Comment by tseaver** [comment]
While we are fixing this one, we should also remove the `timeout` argument to `Connection` -- the underlying instance / client don't take it any more.

**Comment by sduskis** [comment]
@tseaver can we close this?

**Comment by tseaver** [comment]
@sduskis yes.

@sumit-ql The [Github syntax for auto-closing issues](https://help.github.com/articles/closing-issues-using-keywords/) expects the "command" to be on a separate line, rather than embedded in another sentence.  E.g.:

```
Closes #9999
```
